
--Registrar una nueva LINEAS_FACTURA
EXECUTE HR.PK_LINEAS_FACTURAS.ALTA_LINEA(1,1,10,SYSDATE);
EXECUTE HR.PK_LINEAS_FACTURAS.ALTA_LINEA(2,1,15,SYSDATE);
EXECUTE HR.PK_LINEAS_FACTURAS.ALTA_LINEA(3,1,7,SYSDATE);
EXECUTE HR.PK_LINEAS_FACTURAS.ALTA_LINEA(4,1,9,SYSDATE);
EXECUTE HR.PK_LINEAS_FACTURAS.ALTA_LINEA(5,1,18,SYSDATE);


--Funcion para modificar las UNIDADES en LINEAS_FACTURA por medio de (COD_FACTURA, COD_PRODUCTO, UNIDADES_NUEVAS)
DECLARE
    N_UNIDADES NUMBER;
BEGIN
    N_UNIDADES := HR.PK_LINEAS_FACTURAS.MOD_LINEA(1,1,2);
    DBMS_OUTPUT.PUT_LINE(N_UNIDADES);
END;


--Funcion para modificar la FECHA en LINEAS_FACTURA por medio de (COD_FACTURA, COD_PRODUCTO, FECHA_NUEVA)
DECLARE
    N_FECHA DATE;
BEGIN
    N_FECHA:= '2024-02-09 14:00:00';
    N_FECHA := HR.PK_LINEAS_FACTURAS.MOD_LINEA(1,1,N_FECHA);
    DBMS_OUTPUT.PUT_LINE(N_FECHA);
END;


--Funcion para obtener el TOTAL_LINEAS_FACTURA por medio de (COD_FACTURA)
DECLARE
    TOTAL_LINEAS_FACTURA NUMBER;
BEGIN
    TOTAL_LINEAS_FACTURA := HR.PK_LINEAS_FACTURAS.NUM_LINEAS_FAC(1);
    DBMS_OUTPUT.PUT_LINE(TOTAL_LINEAS_FACTURA);
END;


--Eliminar un registro en LINEAS_FACTURA por medio de (COD_FACTURA,COD_PRODUCTO) existentes
EXECUTE HR.PK_LINEAS_FACTURAS.BAJA_LINEA(3,1);