create or replace PACKAGE PK_LINEAS_FACTURAS
IS
    PROCEDURE ALTA_LINEA(ID_FACTURA NUMBER, ID_PRODUCTO NUMBER, UNIDADES NUMBER, FECHA DATE);
    PROCEDURE BAJA_LINEA(ID_FACTURA NUMBER, ID_PRODUCTO NUMBER);

    FUNCTION MOD_LINEA(ID_FACTURA NUMBER, ID_PRODUCTO NUMBER,UNIDADES NUMBER)
    RETURN NUMBER;

    FUNCTION MOD_LINEA(ID_FACTURA NUMBER, ID_PRODUCTO NUMBER,FECHA DATE)
    RETURN DATE;

    FUNCTION NUM_LINEAS_FAC(ID_FACTURA NUMBER)
    RETURN NUMBER;
END;