create or replace TRIGGER TR_PRODUCTOS
AFTER INSERT OR UPDATE OR DELETE
ON LINEAS_FACTURA FOR EACH ROW

DECLARE
    TOTAL_CAMBIO NUMBER := 0;
BEGIN
    --La funcion NVL evaula un parametro y en caso de ser NULL lo convierte a 0
    IF INSERTING THEN
        UPDATE PRODUCTOS SET TOTAL_VENDIDOS = NVL(TOTAL_VENDIDOS,0) + (:NEW.PVP * :NEW.UNIDADES)
        WHERE COD_PRODUCTO = :NEW.COD_PRODUCTO;
    END IF;

    IF UPDATING THEN
        TOTAL_CAMBIO := (:OLD.PVP * :OLD.UNIDADES) - (:NEW.PVP * :NEW.UNIDADES);
        UPDATE PRODUCTOS SET TOTAL_VENDIDOS = TOTAL_VENDIDOS - TOTAL_CAMBIO
        WHERE COD_PRODUCTO = :NEW.COD_PRODUCTO;
    END IF;

    IF DELETING THEN
        TOTAL_CAMBIO := (:OLD.PVP * :OLD.UNIDADES);
        UPDATE PRODUCTOS SET TOTAL_VENDIDOS = TOTAL_VENDIDOS - TOTAL_CAMBIO
        WHERE COD_PRODUCTO = :OLD.COD_PRODUCTO;
    END IF;
END;