create or replace TRIGGER TR_LINEAS_FACTURAS
BEFORE INSERT OR UPDATE OR DELETE
ON LINEAS_FACTURA

BEGIN
    IF INSERTING THEN
        INSERT INTO CONTROL_LOG(COD_EMPLEADO,FECHA,TABLA,COD_OPERACION)
        VALUES(USER,SYSDATE,'LINEAS_FACTURA','I');
    END IF;

    IF UPDATING THEN
        INSERT INTO CONTROL_LOG(COD_EMPLEADO,FECHA,TABLA,COD_OPERACION)
        VALUES(USER,SYSDATE,'LINEAS_FACTURA','U');
    END IF;

    IF DELETING THEN
        INSERT INTO CONTROL_LOG(COD_EMPLEADO,FECHA,TABLA,COD_OPERACION)
        VALUES(USER,SYSDATE,'LINEAS_FACTURA','D');
    END IF;
END;