create or replace TRIGGER TR_FACTURAS
BEFORE INSERT OR UPDATE OR DELETE
ON FACTURAS

BEGIN
    IF INSERTING THEN
        INSERT INTO CONTROL_LOG(COD_EMPLEADO,FECHA,TABLA,COD_OPERACION)
        VALUES(USER,SYSDATE,'FACTURAS','I');
    END IF;

    IF UPDATING THEN
        INSERT INTO CONTROL_LOG(COD_EMPLEADO,FECHA,TABLA,COD_OPERACION)
        VALUES(USER,SYSDATE,'FACTURAS','U');
    END IF;

    IF DELETING THEN
        INSERT INTO CONTROL_LOG(COD_EMPLEADO,FECHA,TABLA,COD_OPERACION)
        VALUES(USER,SYSDATE,'FACTURAS','D');
    END IF;
END;